#-------------------------------------------------------------------------------
#Library and installing packages file
#install.packages("paletteer")
#install.packages("dichromat")
#install.packages("tidytree")
#install.packages("ggnewscale")
#install.packages("tidyverse")
#install.packages("reshape2")
#install.packages("ggtreeExtra")
#install.packages("tableHTML")
#install.packages("ape")
#install.packages("remotes")
#install.packages("ggsci")
#install.packages("eoffice")
#install.packages("RRphylo")
#install.packages("treemapify")
#remotes::install_github("djw533/micro.gen.extra")
# https://rdrr.io/github/djw533/micro.gen.extra/

# if (!require("BiocManager", quietly = TRUE))
#   install.packages("BiocManager")
# 
# BiocManager::install("treeio")
# 
# if (!require("BiocManager", quietly = TRUE))
#   install.packages("BiocManager")
# BiocManager::install("ggtree")
# if (!require("BiocManager", quietly = TRUE))
#   install.packages("BiocManager")
# BiocManager::install("Biostrings")
# if (!require("BiocManager", quietly = TRUE))
#   install.packages("BiocManager")
# BiocManager::install("ggtreeExtra")

library(dplyr)
library(remotes)
library("Biostrings")
library(tidyverse)
library(ggplot2)
library(reshape2)
library(ggtree) 
library(treeio)
library(ggrepel)
library(gridExtra)
library(plotly)
library(kableExtra)
library(knitr)
library(patchwork)
library(xtable)
library(ape)
library(ggnewscale)
library(ggtreeExtra)
library(tidytree)
library(ggsci)
library(dichromat)
library(paletteer)
library(tableHTML)
library(eoffice)
library(RRphylo)
library(scales)
library(treemapify)

# All of the citations for libraries used in this project
citation()
citation("remotes")
citation("Biostrings")
citation("tidyverse")
citation("ggplot2")
citation("reshape2")
citation("ggtree")
citation("treeio")
citation("ggrepel")
citation("gridExtra")
citation("plotly")
citation("kableExtra")
citation("knitr")
citation("patchwork")
citation("xtable")
citation("ape")
citation("ggnewscale")
citation("ggtreeExtra")
citation("tidytree")
citation("ggsci")
citation("dichromat")
citation("paletteer")
citation("tableHTML")
citation("eoffice")
citation("RRphylo")
citation("scales")
citation("treemapify")

